spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shopapp"
    username: root
    password: 5404
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: false
  profiles:
    active: prod

server:
  port: 8088

jwt:
  signer-key: "CxW6hqQc4k77nN0/pbBQL1Gc00MHbtCNrBEi2mlqhEoivDfxUBznMQnIVqWNFWYy"
  valid-duration: 20 # in seconds
  refreshable-duration: 60 # in seconds